### ISSUE TITLE
TemplateNotFound

### ISSUE THREAD

**Issue by nnewram** [Eboreg/mrkoll-scraper#1]
scraper.py:93
kastar jinja2.exceptions.TemplateNotFound: entry.html

python version 3.6.9,
linux mint 19.3
installerat med pip3

**Comment by Eboreg** [comment]
Ursäkta sent svar och tack för heads up. Jag hade missat att inkludera template-katalogen i pypi-paketet. :roll_eyes: Detta ska vara fixat i v0.3.2 som ligger uppe nu, testa gärna att uppgradera.

**Comment by nnewram** [comment]
Japp funkar med
pip3 install -Iv mrkoll-scraper==0.3.2
nice
